name: Update Resume PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-lang-all texlive-fonts-extra latexmk

    - name: Set up LaTeX environment
      uses: dante-ev/latex-action@latest
      with:
        root_file: main.tex

    - name: Clean Up
      run: latexmk -C

    - name: Compile LaTeX document
      run: latexmk -pdf -silent -cd main.tex

    - name: Display LaTeX Log
      if: failure()
      run: cat main.log

    - name: Checkout website repo
      uses: actions/checkout@v3
      with:  
        repository: Yatinkukreja/Personal-Website
        token: ${{ secrets.GITHUB_TOKEN }}
        path: website

    - name: delete old resume pdf
      run: rm website/frontend/public/main.pdf

    - name: copy new resume to website
      run: cp main.pdf website/frontend/public

    - name: commit and push to website repo
      working-directory: website
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add frontend/public/main.pdf
        git commit -m "updated resume"
        git push origin main
